# Generated by Django 4.2.5 on 2023-10-06 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Название авиазапчасти', max_length=100, verbose_name='Название')),
                ('status', models.IntegerField(choices=[(1, 'Действует'), (2, 'Удалена')], default=1, verbose_name='Статус')),
                ('image', models.ImageField(default='spares/default.jpg', upload_to='spares', verbose_name='Фото')),
                ('description', models.TextField(default='Описание авиазапчасти', max_length=500, verbose_name='Описание')),
                ('price', models.IntegerField(default=1000, verbose_name='Цена')),
                ('weight', models.FloatField(default=10.0, verbose_name='Вес')),
                ('condition', models.IntegerField(choices=[(1, 'Новое'), (2, 'Б/У')], default=1, verbose_name='Состояние')),
                ('rating', models.FloatField(default=4.5, verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Авиазапчасть',
                'verbose_name_plural': 'Авиазапчасти',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Введён'), (2, 'В работе'), (3, 'Завершён'), (4, 'Отменён'), (5, 'Удалён')], default=1, max_length=100, verbose_name='Статус')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 10, 6, 9, 16, 10, 658558, tzinfo=datetime.timezone.utc), verbose_name='Дата создания')),
                ('date_of_formation', models.DateTimeField(default=datetime.datetime(2023, 10, 6, 9, 16, 10, 658558, tzinfo=datetime.timezone.utc), verbose_name='Дата формирования')),
                ('date_complete', models.DateTimeField(default=datetime.datetime(2023, 10, 6, 9, 16, 10, 658558, tzinfo=datetime.timezone.utc), verbose_name='Дата завершения')),
                ('spares', models.ManyToManyField(to='spares.spare', verbose_name='Авиазапчасти')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
