# Generated by Django 4.2.4 on 2023-09-16 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(upload_to='spares/', verbose_name='Фото')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('price', models.IntegerField(default=1000, verbose_name='Цена')),
                ('weight', models.FloatField(default=10.0, verbose_name='Вес')),
                ('condition', models.IntegerField(choices=[('Б/У', 'Б/У'), ('Новое', 'Новое')], default='Новое', verbose_name='Состояние')),
                ('rating', models.FloatField(default=4.5, verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Авиазапчасть',
                'verbose_name_plural': 'Авиазапчасти',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Enabled', 'Действует'), ('Deleted', 'Удалена')], default='Введён', max_length=100, verbose_name='Статус')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 9, 16, 16, 43, 15, 872950, tzinfo=datetime.timezone.utc), verbose_name='Дата создания')),
                ('date_of_formation', models.DateTimeField(default=datetime.datetime(2023, 9, 16, 16, 43, 15, 872950, tzinfo=datetime.timezone.utc), verbose_name='Дата формирования')),
                ('date_complete', models.DateTimeField(default=datetime.datetime(2023, 9, 16, 16, 43, 15, 872950, tzinfo=datetime.timezone.utc), verbose_name='Дата завершения')),
                ('spares', models.ManyToManyField(to='spares.spare', verbose_name='Авиазапчасти')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
