# Generated by Django 4.2.4 on 2023-09-16 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_complete',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 16, 16, 46, 4, 438720, tzinfo=datetime.timezone.utc), verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 16, 16, 46, 4, 438720, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_formation',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 16, 16, 46, 4, 438720, tzinfo=datetime.timezone.utc), verbose_name='Дата формирования'),
        ),
        migrations.AlterField(
            model_name='spare',
            name='condition',
            field=models.CharField(choices=[('Б/У', 'Б/У'), ('Новое', 'Новое')], default='Новое', verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='spare',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='spares/', verbose_name='Фото'),
        ),
    ]
