# Generated by Django 4.2.5 on 2024-01-16 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0002_alter_order_date_created_alter_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 16, 58, 50, 959337, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
