# Generated by Django 4.2.4 on 2023-09-17 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0005_alter_order_date_complete_alter_order_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='spares',
            new_name='spare',
        ),
        migrations.AlterField(
            model_name='order',
            name='date_complete',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 17, 10, 35, 59, 998678, tzinfo=datetime.timezone.utc), verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 17, 10, 35, 59, 998678, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_formation',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 17, 10, 35, 59, 998678, tzinfo=datetime.timezone.utc), verbose_name='Дата формирования'),
        ),
        migrations.AlterField(
            model_name='spare',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='spare',
            name='image',
            field=models.ImageField(default='spares/default.jpg', upload_to='spares', verbose_name='Фото'),
        ),
    ]
